# Generated by Django 4.2.9 on 2025-02-24 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_card_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="is_foil",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="notes",
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("tcg", models.CharField(max_length=100)),
                ("total_cards", models.PositiveIntegerField()),
                ("image_url", models.URLField()),
                ("release_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
    ]
