# Generated by Django 4.2.9 on 2025-02-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg7", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg30", models.DecimalField(decimal_places=2, max_digits=10)),
                ("daily_price", models.JSONField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="api.card",
                    ),
                ),
            ],
            options={
                "ordering": ["card"],
            },
        ),
    ]
