# Generated by Django 4.2.9 on 2025-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_cardprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprice",
            name="daily_price",
            field=models.JSONField(default=dict),
        ),
    ]
