# Generated by Django 4.2.20 on 2025-03-21 16:03

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_cardprice_daily_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"Unique": "Un utilisateur avec cet email existe déjà"},
                max_length=254,
                unique=True,
                validators=[api.validators.validate_email_domain],
            ),
        ),
    ]
