# Generated by Django 4.2.20 on 2025-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("COMMON", "Common"),
                    ("UNCOMMON", "Uncommon"),
                    ("RARE", "Rare"),
                    ("HOLORARE", "Holo Rare"),
                    ("HOLORAREGX", "Holo Rare GX"),
                    ("HOLORAREEX", "Holo Rare EX"),
                    ("HOLORARELVX", "Holo Rare LV.X"),
                    ("HOLORARESTARRARE", "Holo Rare ★"),
                    ("BREAKRARE", "Rare BREAK"),
                    ("PRIMERARE", "Rare Prime"),
                    ("PRISMRARE", "Rare Prism Star"),
                    ("RAINBOWRARE", "Rare Rainbow"),
                    ("SHININGRARE", "Rare Shining"),
                    ("SHINYRARE", "Rare Shiny"),
                    ("SHINYRAREGX", "Rare Shiny GX"),
                    ("HOLORAREV", "Holo Rare V"),
                    ("HOLORAREVMAX", "Holo Rare VMAX"),
                    ("HOLORAREVSTAR", "Holo Rare VSTAR"),
                    ("ULTRARARE", "Ultra Rare"),
                    ("ACERARE", "Rare ACE"),
                    ("SECRETRARE", "Secret Rare"),
                    ("ILLUSTRATIONRARE", "Illustration Rare"),
                    ("SPECIALILLUSTRATIONRARE", "Special Illustration Rare"),
                    ("DOUBLERARE", "Double Rare"),
                    ("TRIPLERAARE", "Triple Rare"),
                    ("PROMO", "Promo"),
                    ("LEGENDRARE", "Legend Rare"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=50,
            ),
        ),
    ]
