# Generated by Django 4.2.20 on 2025-06-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_card_rarity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="set",
            unique_together={("code",)},
        ),
        migrations.RemoveField(
            model_name="set",
            name="user",
        ),
    ]
