# Generated by Django 4.2.20 on 2025-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_set_unique_together_remove_set_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
