# Generated by Django 4.2.20 on 2025-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_set_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="symbol_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
