# Generated by Django 4.2.20 on 2025-06-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_set_symbol_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="card",
            name="set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.set",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("set", "number")},
        ),
        migrations.RemoveField(
            model_name="card",
            name="set_name",
        ),
        migrations.CreateModel(
            name="UserSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_count", models.IntegerField(default=0)),
                ("total_cards", models.IntegerField(default=0)),
                ("completion", models.FloatField(default=0.0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.set"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "set")},
            },
        ),
    ]
