# Generated by Django 4.2.20 on 2025-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_card_unique_together_card_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userset",
            name="completion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
