# Generated by Django 4.2.20 on 2025-07-04 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_userset_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="clip_embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=512
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="descriptors",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="histogram",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="phash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
