# Generated by Django 4.2.20 on 2025-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_card_clip_embedding_card_descriptors_card_histogram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="clip_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="histogram",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
